### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by parmindersingh1** [bkbilly/AlarmPI#1]
i m getting this error
sudo service alarmpi status
cat: /var/run/alarmpi/alarmpi.pid: No such file or directory
AlarmPI not running.

**Comment by bkbilly** [comment]
You will have to make sure you have the latest release. To do this write this command on your raspberry:`bash <(curl -s "https://raw.githubusercontent.com/bkbilly/AlarmPI/master/install.sh")`

If it doesn't work, run it manually:
`cd /opt/AlarmPI`
`python alarmpi.py`

If there is still a problem, send me the output of the manual run.

**Comment by bkbilly** [comment]
I believe that I found the solution. I've updated the code, so you will have to update your version too.

The problem was that it was trying to read the alert.log file before it was created.

I will close this issue. If you still have a problem please send me the output of the manual run that I wrote to you above.

Thanks!

**Comment by parmindersingh1** [comment]
ok thanks

**Comment by parmindersingh1** [comment]
sudo python alarmpi.py 
------------ INIT FOR DOOR SENSOR CLASS! ----------------
MQTT: Invalid host.
Traceback (most recent call last):
  File "alarmpi.py", line 415, in <module>
    myserver.startServer()
  File "alarmpi.py", line 403, in startServer
    ssl_context=context)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 526, in run
    log=log, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 1405, in __init__
    StreamServer.__init__(self, listener, backlog=backlog, spawn=spawn, **ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 96, in __init__
    self.wrap_socket = ssl_context.wrap_socket
AttributeError: 'NoneType' object has no attribute 'wrap_socket'

**Comment by bkbilly** [comment]
You should try installing gevent and then removing it.
`sudo pip install gevent`
`sudo pip uninstall gevent`

I am still searching for the reason this happens.
Please inform me if it works.

**Comment by parmindersingh1** [comment]
it worked thanks

**Comment by bkbilly** [comment]
You're welcome!
