### ISSUE TITLE
mqtt problem with iobroker.mqtt

### ISSUE THREAD

**Issue by stratogk** [bkbilly/AlarmPI#16]
(14038) Client [1965] Message 12 deleted after 11 retries
--

**Comment by bkbilly** [comment]
Can you explain better what is the problem and even write the system logs (sysrun.log) with the error you get?

**Comment by stratogk** [comment]
my sysrun.log 

2020-03-08 11:48:31 [INFO] [notifier:on_message_mqtt:234]  myhome/alarm/set 
2020-03-08 11:48:31 [INFO] [notifier:on_message_mqtt:234]  myhome/alarm/set/sensor/pir1 
2020-03-08 11:48:31 [ERROR] [notifier:on_message_mqtt:262]  Unknown MQTT Error:
Traceback (most recent call last):
  File "/opt/AlarmPI/alarmcode/notifier.py", line 252, in on_message_mqtt
    self.callbacks['sensorStopAlert'](sensor)
TypeError: <lambda>() takes 0 positional arguments but 1 was given

**Comment by bkbilly** [comment]
I did an update that might fix it, but couldn't find the route cause of the problem.
Can you provide me with the configuration files from the config file?
Remove any password that might exist or any other sensitive info you have.

In the meantime you can try to update to the newer version of the app with this command:
`bash <(curl -s "https://raw.githubusercontent.com/bkbilly/AlarmPI/master/install.sh")`

**Comment by stratogk** [comment]
`{
    "http": {
        "enable": false,
        "host": "alarmpi",
        "https": false,
        "password": "xxx",
        "port": 5050,
        "username": "xxx"
    },
    "mail": {
        "enable": false,
        "messageBody": "Alert",
        "messageSubject": "Home Security",
        "password": "",
        "recipients": [
            ""
        ],
        "smtpPort": 587,
        "smtpServer": "smtp.gmail.com",
        "username": ""
    },
    "mqtt": {
        "authentication": true,
        "command_topic": "myhome/alarm/set",
        "enable": true,
        "homeassistant": false,
        "host": "192.168.0.113",
        "password": "xxx",
        "port": 1886,
        "state_topic": "myhome/alarm",
        "username": "xxx"
    },
    "sensors": {
        "ce11c170-3550-4f9d-9f98-5c22a2130faf": {
            "alert": false,
            "behavior": "normal",
            "enabled": true,
            "name": "pir1",
            "online": true,
            "pin": "12",
            "type": "GPIO",
            "zones": [
                "HOME"
            ]
        }
    },
    "serene": {
        "enable": false,
        "http_start": "",
        "http_stop": "",
        "pin": 14
    },
    "settings": {
        "alarmArmed": false,
        "alarmTriggered": false,
        "timezone": "Europe/Athens",
        "trim": 1000
    },
    "voip": {
        "domain": "",
        "enable": false,
        "numbersToCall": [
            ""
        ],
        "password": "",
        "timesOfRepeat": "",
        "username": ""
    }
}`

**Comment by bkbilly** [comment]
Has the new version that I mentioned above fixed your problem?

**Comment by stratogk** [comment]
kalispera file mou alaksa ton mqtt server se alo rpi kai dulepse eftege o
mqtt server

**Comment by bkbilly** [comment]
Great! Happy you managed to fix it with the new mqtt server.
