### ISSUE TITLE
Voip Issue

### ISSUE THREAD

**Issue by dnacsgo** [bkbilly/AlarmPI#27]
Firstly this is an amazing project.

I am running into an issue with Voip

I use a voip server using MiniSipServer running on a VPS Server I connected number 101 to my phone and 100 to the alarmpi

When an intruder alarm is activated it says Calling 101 and immediately says Call Ended. Without trying to call . Any ideas how to resolve this issue?

Also a suggest If you are interested Add a delay arm setting and allow user to set how many seconds he has until he leaves the house etc. And also door delay for example set in x zone to allow x seconds to disarm else sound alarm

Thank you very mutch and looking forward hearing from you.

Μπορεις να επικοινωνήσεις μαζι μου μέσω viber αμ χρειάζεσαι περισσότερες πληροφορίες στο 6948531588

**Comment by dnacsgo** [comment]
Good evening again I found what what was causing it. libssl1.0.0 was missing and it was causing issues

**Comment by bkbilly** [comment]
I am happy that you could fix it.

As for the delay alarm it would make it very complicated.
There is a feature like this but it works differently. 
The alarm waits for all active sensors to close and then activates the alarm.

**Comment by dnacsgo** [comment]
I just saw! Perfection thank you!

**Comment by JaccoKlaase** [comment]
@bkbilly can this software be run on Debian 11? I have the same problem as @dnacsgo that OpenSSL1.0.0 is missing.
I have made symbolic-links to the files libssl.so.1.0.2 and libcrypto.so.1.0.2 and named them libssl.so.1.0.0 and libcrypto.so.1.0.0 (see screenshot)
Now I have the last message saying that OPENSSL_1.0.0 is not found
Any workarounds?

I want AlarmPI to make a voipcall on alarmevent
![AlarmPI_OpenSSL_error_06022024](https://github.com/bkbilly/AlarmPI/assets/159157975/41a73cca-5d27-44cb-a111-59a7f8f9f2ae)

**Comment by bkbilly** [comment]
The sipcall was built for the Raspberry, so I don't think you can run it on a debian without recompiling it.
You can see installation script that I used for Raspberry here: https://github.com/bkbilly/AlarmPI/blob/master/voip/install_pjsip.sh
It might need some changes to work, but hopefully you will be able to create an executable for debian.

**Comment by JaccoKlaase** [comment]
Hi Vasilis, let me clarify, I’m using a Raspberry PI 4B 8GB with Raspbian Bullseye 32-Bit Legacy installed.

**Comment by bkbilly** [comment]
You could try installing the dependencies from my installation script which also contain the library for the SSL (libssl-dev)

**Comment by JaccoKlaase** [comment]
Hi Vasilis, ty for your reply.
Are those different from your installation script? If so how would I install this? Just by starting your install-script?
I have already tried to install libssl-dev and libssl1.0-dev through the apt-get install command (only one is allowed, the other is removed when installing)
The lowest version of the libssl-package that was available on Raspbian Bullseye for install was libssl1.0-dev which installs libssl.so.1.0.2 and libcrypto.so.1.0.2. Sipcall asks for versions 1.0.0, but by creating links to the 1.0.2 versions that works but then Sipcall is asking for OpenSSL version 1.0.0..... and then I'm stuck (see screenshot from earlier post)
