### ISSUE TITLE
Mqtt and Home assistant 

### ISSUE THREAD

**Issue by Amorphous88** [bkbilly/AlarmPI#28]
**Describe the problem**

**OS Version**

**AlarmPI version** 

**Error Logs**

```txt

```

**Configuration**

```json

```
HI.
could you be clearer how to configure the anti-theft and the mqtt file in home assistant to have all the features?
i managed to interface it once but after a raspberry reboot, mqtt communication was lost and never came back.
when there was communication, every time I entered as home assistant, the burglar alarm automatically excluded any sensor programmed inside it.
i installed the latest updated version on raspberry pi os lite 64 bit ( Raspberry Pi 3a+)
I am not getting any errors from the OS

**Comment by Amorphous88** [comment]
update:
I installed the anti-theft device on Raspberry pi OS lite 32 bit and the problem remains the same.

**Comment by Amorphous88** [comment]
![Screenshot_2023-06-01-13-38-12-96_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/bkbilly/AlarmPI/assets/135159899/951826da-7241-44e1-a174-82e95a316693)

**Comment by Amorphous88** [comment]
![Screenshot_2023-06-01-13-38-36-03_c3a231c25ed346e59462e84656a70e50](https://github.com/bkbilly/AlarmPI/assets/135159899/1a5a4797-3701-4279-9306-464e14a66017)

**Comment by bkbilly** [comment]
For MQTT to work and Home Assistant to discover it as a device you will have to configure AlarmPI like this:
![image](https://github.com/bkbilly/AlarmPI/assets/518494/0599ee26-2c83-42ca-938c-928e7a699ed7)

Make sure the **HomeAssistant Integration** is **true** and the button for MQTT on the top right is green.
On Home assistant, the newly discovered device will be under the MQTT integration on the devices.

**Comment by Amorphous88** [comment]
Hi, thankyou.
I did as you say, but there are problems that I wrote to you.
when I insert from the home assistant it excludes all the sensors in any type of insertion.
if I restart Raspberry with OS alarmPi, the integration doesn't work anymore

**Comment by bkbilly** [comment]
Try changing the Authentication field to true, even though you might not have username/password authentication on your mqtt server.

**Comment by Amorphous88** [comment]
![Screenshot_2023-06-02-16-13-44-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/bkbilly/AlarmPI/assets/135159899/4e811e09-1709-463d-bf85-27fb58f269b3)

I don't have active authentications. in fact, as soon as the system is installed and mqtt started with the credentials with home assistant, I have the states and commands, even if every time I insert from the home assistant all the sensors are automatically excluded in AlarmPi. it's when I restart alarmPi that everything is lost.
This problem I'm experiencing is really strange and I haven't found a solution

**Comment by bkbilly** [comment]
I can't seem to understand what could be the reason for the problem you have. You could try, if possible, connect radpberry with ethernet.

**Comment by Amorphous88** [comment]
could it be the mqtt script in yaml configuration?
i tried many times but nothing changed.
when it works, however, the script is absent because home assistant detects everything automatically.
do you enter it?
how exactly do you write it to have all the states and commands?

**Comment by bkbilly** [comment]
You don't have to change anything on the yaml configuration, everything is changed by the UI.
If you want to understand how the Home assistant discovers the commands, you will have to check their documentation. It's difficult to explain it here.
I am curious about this problem so I could try connecting to your system to check why this is happening.

**Comment by Amorphous88** [comment]
HI.
my email is mario.naclerio@yahoo.it.
let's get in touch so we can arrange the connection with anydesk
